[package]
name = "icy_redis_viewer"
version = "0.1.0"
authors = ["Sorrien <collin.sparks@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "0.20.0"
iced = "0.3.0"
generational-arena = "0.2"